### ISSUE TITLE
`vrotsc` should show better errors if you're using a decorator but the filename is not correct

### ISSUE THREAD

**Issue by Michaelpalacce** [vmware/build-tools-for-vmware-aria#301]
### Description

There is an issue when you want to create a Workflow, ConfigurationElement, PolicyTemplate, etc that have a special naming convention with a Decorator, where if the file is not named correctly, an error that has nothing to do with the issue will be thrown.

We want a better error indicating the actual problem if there are any known decorators ( @Workflow, @Configuration, etc).

Error originates from `vrotsc` but is thrown in `vropkg`. `vrotsc` should detect the decorator and throw if the name is not good.

### Steps to Reproduce

1. Create a new typescript project
2. Create a file in `src/workflows` called test.wf
3. Add a Workflow in the test.wf file
4. Run `mvn clean package`

**Expected behavior:** Meaningful error is thrown

**Actual behavior:** the error given down in this bug report is thrown

**Reproduces how often:** 100%

**Component/s:** `typescript/vrotsc`, `typescript/vropkg`

**Affects Build/s:** All

### Failure Logs

```logs
[INFO] --- vro:2.35.1:package (default-package) @ sgenov ---
[INFO] Project basedir: /Users/sgenov/projects/testing/personal
[INFO] Package name 'com.vmware.pscoe.onboarding.sgenov-4.0.0-SNAPSHOT
[INFO] Building vRO package 'com.vmware.pscoe.onboarding.sgenov-4.0.0-SNAPSHOT.package' to: /Users/sgenov/projects/testing/personal/target
[INFO] Running vropkg... started
[INFO] info: Parsing vro javascript project folder path "/Users/sgenov/projects/testing/personal/target/vro-sources/js"...
[ERROR] /Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/dist/parse/js.js:210
[ERROR]             throw new Error(`${jsFile} ${ex.message}\n ${ex.stack}`);
[ERROR]                   ^
[ERROR]
[ERROR] Error: /Users/sgenov/projects/testing/personal/target/vro-sources/js/src/main/resources/com/vmware/pscoe/onboarding/sgenov/workflows/test.js [9:15]: Unexpected token: '-'
[ERROR]  SyntaxError: [9:15]: Unexpected token: '-'
[ERROR]     at report (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:186:11)
[ERROR]     at matchOrInsertSemicolon (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4368:9)
[ERROR]     at parseVariableStatement (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:5365:5)
[ERROR]     at parseStatement (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4906:20)
[ERROR]     at parseStatementListItem (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4900:20)
[ERROR]     at parseFunctionBody (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:6106:19)
[ERROR]     at parseFunctionExpression (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:6703:18)
[ERROR]     at parsePrimaryExpression (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:6381:20)
[ERROR]     at parseParenthesizedExpression (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:7681:20)
[ERROR]     at parsePrimaryExpression (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:6387:20)
[ERROR]     at parseExpressionOrLabelledStatement (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4965:20)
[ERROR]     at parseStatement (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4950:20)
[ERROR]     at parseStatementListItem (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4900:20)
[ERROR]     at parseModuleItem (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4864:26)
[ERROR]     at parseModuleItemList (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4849:25)
[ERROR]     at parseSource (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/node_modules/meriyah/dist/meriyah.cjs:4793:16)
[ERROR]     at Function.getSourceTreeFromSource (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/dist/parse/js.js:210:19)
[ERROR]     at VroJsProjParser.<anonymous> (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/dist/parse/js.js:50:50)
[ERROR]     at Array.forEach (<anonymous>)
[ERROR]     at VroJsProjParser.<anonymous> (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/dist/parse/js.js:32:69)
[ERROR]     at Generator.next (<anonymous>)
[ERROR]     at /Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/dist/parse/js.js:8:71
[ERROR]     at new Promise (<anonymous>)
[ERROR]     at __awaiter (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/dist/parse/js.js:4:12)
[ERROR]     at VroJsProjParser.parse (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/dist/parse/js.js:27:16)
[ERROR]     at /Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/dist/cli.js:112:57
[ERROR]     at Generator.next (<anonymous>)
[ERROR]     at /Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/dist/cli.js:8:71
[ERROR]     at new Promise (<anonymous>)
[ERROR]     at __awaiter (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/dist/cli.js:4:12)
[ERROR]     at run (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/dist/cli.js:54:12)
[ERROR]     at Object.<anonymous> (/Users/sgenov/projects/testing/personal/node_modules/@vmware-pscoe/vropkg/dist/cli.js:151:1)
[INFO] Running vropkg... finished
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.884 s
[INFO] Finished at: 2024-07-10T17:24:31+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:o11n-typescript-package-maven-plugin:2.35.1:package (default-package) on project sgenov: Running vropkg... failed with code 1 -> [Help 1]
[ERROR]
```

### Additional Context

<img width="1728" alt="image" src="https://github.com/vmware/build-tools-for-vmware-aria/assets/17056014/dcff16ec-ca91-44f0-a06d-ce79249a5724">

**Comment by VenelinBakalov** [comment]
I didn't fully get the issue here, we probably discussed it already but honestly, i forgot. Is this related to the name of the decorator, the name of the workflow or the extension?
I tried creating a workflow with .wf extension in ts project (with and without code content) and the build seems to ignore it and not throw an error.
![image](https://github.com/user-attachments/assets/05174215-6124-4f42-b1ab-3ea283b9ac2b)
