### ISSUE TITLE
Toolchain 3.1.1 does not compile Jasmine unit tests

### ISSUE THREAD

**Issue by igormicev** [vmware/build-tools-for-vmware-aria#557]
### Description

Toolchain version 3.1.1
Java 17
Node v20
 
Tests fail to compile.
 
 
[INFO] Installing node modules for the tests.
[ERROR] node:internal/errors:984
[ERROR]   const err = new Error(message);
[ERROR]           	^
[ERROR]
[ERROR] Error: Command failed: npm install
[ERROR] 	at genericNodeError (node:internal/errors:984:15)
[ERROR] 	at wrappedFn (node:internal/errors:538:14)
[ERROR] 	at checkExecSyncError (node:child_process:890:11)
[ERROR] 	at Object.execSync (node:child_process:962:15)
[ERROR] 	at D:\CUSERID\code\xxxxx-dispatcher\vro\node_modules\@vmware-pscoe\vrotest\lib\vrotest.js:1:244643
[ERROR] 	at de.withWorkingDir (D:\CUSERID\code\sap-hec-dispatcher\vro\node_modules\@vmware-pscoe\vrotest\lib\vrotest.js:1:228653)
[ERROR] 	at ms.default (D:\CUSERID\code\xxxxx-dispatcher\vro\node_modules\@vmware-pscoe\vrotest\lib\vrotest.js:1:244559)
[ERROR] 	at D:\CUSERID\code\xxxxx-dispatcher\vro\node_modules\@vmware-pscoe\vrotest\lib\vrotest.js:1:246718
[ERROR] 	at D:\CUSERID\code\xxxxx-dispatcher\vro\node_modules\@vmware-pscoe\vrotest\lib\vrotest.js:1:246724
[ERROR] 	at Object.<anonymous> (D:\CUSERID\code\xxxxx-dispatcher\vro\node_modules\@vmware-pscoe\vrotest\lib\vrotest.js:1:246729) {
[ERROR]   status: 1,
[ERROR]   signal: null,
[ERROR]   output: [ null, null, null ],
[ERROR]   pid: 872,
[ERROR]   stdout: null,
[ERROR]   stderr: null
[ERROR] }
[ERROR]
[ERROR] Node.js v20.12.2
[ERROR] ERROR: Coverage for lines (0%) does not meet global threshold (55%)
[ERROR] ERROR: Coverage for functions (0%) does not meet global threshold (55%)
[ERROR] ERROR: Coverage for branches (0%) does not meet global threshold (55%)
[ERROR] ERROR: Coverage for statements (0%) does not meet global threshold (55%)

### Steps to Reproduce

1. mvn clean package

**Preconditions:** [What are the preconditions to reproduce the issue]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce]

**Component/s:** [What are the Build Tools for VMware Aria components affected by the issue (e.g. "common/artifact-manager", "maven/plugins/vra-ng", "typescript/vrotest", etc)]

typescript/vrotest

**Affects Build/s:** [Which are the Build Tools for VMware Aria releases / builds affected by the issue]

#### Client

- Build Tools for VMware Aria Version: 2.39.0
- Visual Studio Code Version: 1.91.1
- OS Version: Windows Server 2019 Standard, Version 1809, OS Build 17763.5936

#### Dependencies

Run: `curl -o- https://raw.githubusercontent.com/vmware/build-tools-for-vmware-aria/main/health.sh | bash` and paste the output here:

The environment doesn't have access to the curl link.

#### Server

- vRealize Automation Version:
- vRealize Orchestrator Version:
- vRealize Operations Version:
- vRealize Log Insight Version:

### Failure Logs

[INFO] vro ................................................ FAILURE [06:21 min]
[INFO] vra ................................................ SKIPPED
[INFO] xxx-ops-automation ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:22 min
[INFO] Finished at: 2024-12-05T08:54:12Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vmware.pscoe.maven.plugins:o11n-typescript-package-maven-plugin:3.1.1:run-vro-tests (default-run-vro-tests) on project vro: One or more v
RO tests failed -> [Help 1]
[ERROR]

+
from the description.

### Additional Context
node -v
v20.12.2

java --version
openjdk 17.0.10 2024-01-16 LTS
OpenJDK Runtime Environment (build 17.0.10+7-LTS)
OpenJDK 64-Bit Server VM (build 17.0.10+7-LTS, mixed mode, sharing)

**Comment by igormicev** [comment]
Issue discussed.
Error: Command failed: npm install
tells the user that access to NPM is not working.
